name: flutter_demo
description: "A demo flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_common:
    git:
      url: https://github.com/MohamadAllahham/flutter_common.git
      ref: main

  cupertino_icons: ^1.0.8
  intl: 0.19.0 # adds support for different language files
  localstorage: ^5.0.0 # simple json file-based storage
  json_annotation: ^4.9.0 # defines annotations for JSON (de)serialization.
  auto_route: ^9.3.0+1 # improved navigation and guarded routes
  get_it: ^8.0.3 # simple service locator
  flutter_bloc: ^9.0.0 # state management via observables
  flutter_dotenv: ^5.2.1 # runtime config from a .env file
  package_info_plus: ^8.2.1 # access info from pubspec.yaml
  file_picker: ^9.0.1 # file picking dialog on major platforms
  font_awesome_flutter: ^10.8.0 # additional icons, especially for logos
  styled_text: ^8.1.0 # parse strings for XML tags to create styled text
  multi_select_flutter: ^4.1.3 # material style widgets to select multiple options at once
  flutter_staggered_grid_view: ^0.7.0 # provide masonry and staggered placement for widgets
  universal_html: ^2.2.4 # eases cross-platform development by replacing dart:html
  screenshot: ^3.0.0 # convert off-screen widgets into images printing
  printing: ^5.14.2 # create pdf files and call the printer image
  image: ^4.5.3 # load, save and manipulate images

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  widgetbook: ^3.11.0 # isolated view of widgets
  build_runner: ^2.4.15 # a concrete way of generating files using Dart code
  json_serializable: ^6.9.4 # Dart Build System builders for handling JSON
  source_gen: ^2.0.0 # utilities for automated source code generation
  auto_route_generator: ^9.3.1 # generation of auto_route files
  flutter_gen_runner: # generation of asset code
  mocktail: ^1.0.4 # automatic mocks for unit testing

flutter_gen:
  output: .dart_tool/flutter_gen/

flutter:
  uses-material-design: true
  generate: true
